  -  name: Installing Httpd Server.
     yum:
       name: httpd
       state: installed
  -  name: Ensure httpd is running.
     service:
       name: httpd
       state: started
       enabled: yes
  -  name: Replaces ServerAdmin email in the httpd config file.
     ansible.builtin.lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin ademir@myproject.com
