---
version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    container_name: valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - /home/cevap/valheim-server/config:/config
      - /home/cevap/valheim-server/data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - /home/cevap/valheim-server/valheim.env
    restart: always
