  -  name: Updates the server.
     command: yum update -y
  -  name: Runs update every midnight.
     ansible.builtin.cron:
       name: "Midnight update."
       minute: "0"
       hour: "0"
       job: "yum update -y"
